joint_control_demo:
  ros__parameters:

    topic_name: "/position_trajectory_controller/joint_trajectory"
    wait_sec_between_publish: 6.0

    goal_names: ["pos1", "pos2"]
    pos1: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
    pos2: [-0.3, -0.3, -0.3, -0.3, -0.3, -0.3, -0.3]

    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
